var config = config || {};
config.animations = {
  "ant-body-hit": [
    "ant-body-hit-1",
    "ant-body-hit-2",
    "ant-body-hit-1",
    "ant-body-hit-3"
  ],
  "ant-body-still-left": ["ant-body-walk-left-1"],
  "ant-body-still-right": ["ant-body-walk-right-1"],
  "ant-body-walk-left": [
    "ant-body-walk-left-2",
    "ant-body-walk-left-3",
    "ant-body-walk-left-4",
    "ant-body-walk-left-5"
  ],
  "ant-body-walk-right": [
    "ant-body-walk-right-2",
    "ant-body-walk-right-3",
    "ant-body-walk-right-4",
    "ant-body-walk-right-5"
  ],
  "ant-head-left": [
    "ant-head-left-1",
    "ant-head-left-1",
    "ant-head-left-1",
    "ant-head-left-1",
    "ant-head-left-1",
    "ant-head-left-1",
    "ant-head-left-1",
    "ant-head-left-1",
    "ant-head-left-1",
    "ant-head-left-1",
    "ant-head-left-1",
    "ant-head-left-1",
    "ant-head-left-2",
    "ant-head-left-3",
    "ant-head-left-2"
  ],
  "ant-head-right": [
    "ant-head-right-1",
    "ant-head-right-1",
    "ant-head-right-1",
    "ant-head-right-1",
    "ant-head-right-1",
    "ant-head-right-1",
    "ant-head-right-1",
    "ant-head-right-1",
    "ant-head-right-1",
    "ant-head-right-1",
    "ant-head-right-1",
    "ant-head-right-1",
    "ant-head-right-2",
    "ant-head-right-3",
    "ant-head-right-2"
  ],
  "ant-head-hit": ["ant-head-hit-1", "ant-head-hit-2", "ant-head-hit-3"],
  "ant-weapon-bazooka-left": ["ant-weapon-bazooka-left"],
  "ant-weapon-bazooka-right": ["ant-weapon-bazooka-right"],
  "ant-weapon-laser-left": ["ant-weapon-laser-left"],
  "ant-weapon-laser-right": ["ant-weapon-laser-right"],
  "ant-weapon-throw-left": ["ant-weapon-throw-left-1"],
  "ant-weapon-throw-fire-left": [
    "ant-weapon-throw-left-2",
    "ant-weapon-throw-left-3",
    "ant-weapon-throw-left-4",
    "ant-weapon-throw-left-5",
    "ant-weapon-throw-left-1",
    "ant-weapon-throw-left-1",
    "ant-weapon-throw-left-1",
    "ant-weapon-throw-left-1",
    "ant-weapon-throw-left-1"
  ],
  "ant-weapon-throw-right": ["ant-weapon-throw-right-1"],
  "ant-weapon-throw-fire-right": [
    "ant-weapon-throw-right-2",
    "ant-weapon-throw-right-3",
    "ant-weapon-throw-right-4",
    "ant-weapon-throw-right-5",
    "ant-weapon-throw-right-1",
    "ant-weapon-throw-right-1",
    "ant-weapon-throw-right-1",
    "ant-weapon-throw-right-1",
    "ant-weapon-throw-right-1"
  ],
  "ant-weapon-dig-left": ["ant-weapon-dig-left-1"],
  "ant-weapon-dig-fire-left": [
    "ant-weapon-dig-left-2",
    "ant-weapon-dig-left-3",
    "ant-weapon-dig-left-4"
  ],
  "ant-weapon-dig-right": ["ant-weapon-dig-right-1"],
  "ant-weapon-dig-fire-right": [
    "ant-weapon-dig-right-2",
    "ant-weapon-dig-right-3",
    "ant-weapon-dig-right-4"
  ],
  "ant-ghost": [
    "ant-ghost-1",
    "ant-ghost-1",
    "ant-ghost-2",
    "ant-ghost-2",
    "ant-ghost-3",
    "ant-ghost-3",
    "ant-ghost-2",
    "ant-ghost-2"
  ],
  "bubble-blue": [
    "ball-blue-1",
    "ball-blue-2",
    "ball-blue-3",
    "ball-blue-4",
    "ball-blue-5"
  ],
  "explosion-l": [
    "explosion-l-1",
    "explosion-l-2",
    "explosion-l-3",
    "explosion-l-4",
    "explosion-l-5",
    "explosion-l-6",
    "explosion2-l-5",
    "explosion2-l-6",
    "explosion2-l-7",
    "explosion2-l-8"
  ],
  "explosion2-l": [
    "explosion2-l-1",
    "explosion2-l-2",
    "explosion2-l-3",
    "explosion2-l-4",
    "explosion2-l-5",
    "explosion2-l-6",
    "explosion2-l-7",
    "explosion2-l-8"
  ],
  "explosion-green-l": [
    "explosion-green-l-1",
    "explosion-green-l-2",
    "explosion-green-l-3",
    "explosion-green-l-4",
    "explosion-green-l-5",
    "explosion-green-l-6",
    "explosion-green-l-7",
    "explosion-green-l-8"
  ],
  "explosion-laser-blue": [
    "explosion-laser-blue-1",
    "explosion-laser-blue-2",
    "explosion-laser-blue-3",
    "explosion-laser-blue-4",
    "explosion-laser-blue-5"
  ],
  flame: ["flame-1", "flame-2", "flame-3", "flame-4", "flame-5"],
  "flame-large": [
    "flame-large-1",
    "flame-large-2",
    "flame-large-3",
    "flame-large-4",
    "flame-large-5",
    "flame-large-6"
  ],
  focus: [
    "focus-1",
    "focus-2",
    "focus-3",
    "focus-4",
    "focus-5",
    "focus-6",
    "focus-7",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8",
    "focus-8"
  ],
  "gem-green": [
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-1",
    "gem-green-2",
    "gem-green-3",
    "gem-green-4"
  ],
  "gem-blue": [
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-1",
    "gem-blue-2",
    "gem-blue-3",
    "gem-blue-4"
  ],
  "gem-red": [
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-1",
    "gem-red-2",
    "gem-red-3",
    "gem-red-4"
  ],
  "gem-purple": [
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-1",
    "gem-purple-2",
    "gem-purple-3",
    "gem-purple-4"
  ],
  "gem-silver": [
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-1",
    "gem-silver-2",
    "gem-silver-3",
    "gem-silver-4"
  ],
  "grenade-armed": [
    "grenade-green",
    "grenade-red",
    "grenade-red",
    "grenade-green",
    "grenade-green",
    "grenade-green",
    "grenade-green",
    "grenade-green",
    "grenade-green",
    "grenade-green",
    "grenade-green",
    "grenade-green"
  ],
  "mine-active": [
    "mine-red",
    "mine-red",
    "mine-grey",
    "mine-grey",
    "mine-grey",
    "mine-grey",
    "mine-grey",
    "mine-grey",
    "mine-grey",
    "mine-grey",
    "mine-grey",
    "mine-grey",
    "mine-grey",
    "mine-grey",
    "mine-grey"
  ],
  "smoke-green": [
    "smoke-green-1",
    "smoke-green-2",
    "smoke-green-3",
    "smoke-green-4",
    "smoke-green-5",
    "smoke-green-6",
    "smoke-green-7",
    "smoke-green-8"
  ],
  teleport: [
    "teleport-1",
    "teleport-2",
    "teleport-3",
    "teleport-4",
    "teleport-5",
    "teleport-6",
    "teleport-7"
  ],
  vortex: [
    "vortex-1",
    "vortex-2",
    "vortex-3",
    "vortex-4",
    "vortex-5",
    "vortex-6",
    "vortex-7",
    "vortex-8",
    "vortex-10",
    "vortex-11"
  ]
};
